name: ShulkerBlocker
main: me.ruud.shulkerblocker.ShulkerBlocker
author: xX4w3s0m3Xx
version: 0.0.2
api-version: 1.13
description: Blocks shulker boxes from chests.
permissions:
  shulkerblocker.*:
    description: Permits the player to put shulker boxes in all types of chests.
    children:
      shulkerblocker.normal: true
      shulkerblocker.double: true
      shulkerblocker.trapped: true
      shulkerblocker.ender: true
      shulkerblocker.donkey: true
      shulkerblocker.hopper: true
  shulkerblocker.normal:
    description: Permits the player to put shulker boxes into normal chests.
  shulkerblocker.double:
    description: Permits the player to put shulker boxes into double chests.
  shulkerblocker.trapped:
    description: Permits the player to put shulker boxes into trapped chests.
  shulkerblocker.ender:
    description: Permits the player to put shulker boxes into ender chests.
  shulkerblocker.donkey:
    description: Permits the player to put shulker boxes into donkey chests.
  shulkerblocker.hopper:
    description: Permits the player to put shulker boxes into hoppers.